#!/bin/bash

read -p "What ruby version? (2.1.1) " input
input=${input:-2.1.1}
echo $input >> .ruby-version
read -p "What gemset (default)? " input
input=${input:-default}
echo $input >> .ruby-gemset
