maintainer        "Sam Bao"
maintainer_email  "sambao21@gmail.com"
license           "MIT"
description       "sambao21's custom workstation recipes"
long_description  IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version           "1.0.0"
supports          "mac_os_x"
depends           "dmg"
depends           "osx"
depends           "homebrew"
depends           "pivotal_workstation"
depends           "sprout-osx-base"
depends           "sprout-osx-settings"
depends           "sprout-osx-apps"
depends           "sprout-osx-git"
depends           "sprout-pivotal"
